"""Add relotionship user

Revision ID: 1767fced9483
Revises: e072ad9efd9d
Create Date: 2023-07-02 20:57:19.785151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1767fced9483'
down_revision = 'e072ad9efd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'user_id')
    # ### end Alembic commands ###
